### ISSUE TITLE
SDD

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-Mobile-Assistant-for-Cryptocurrency-Markets#1]
SDD dokümanında desteklenecek borsa sistelerinden bunların api lerinin kullanımından ve destekledikleri işlemlerden bahsetmekte fayda var. Ayrıca bu api ile data çekme işleminin standardizasyonu için oluşması gereken class yapılarının class diagramlarıyla gösterilmesi gerekir.

Ayrıca assistant kısmında çözümün algoritmasından bahsetmek gerekir.

Bir de ekran mockup ları olsa güzel olurdu. (https://moqups.com/ gibi bir tool yada muadil birşeyler kullanabilirsiniz)

**Comment by berkayjj** [comment]
SDD dökümanının update edilmiş halini github'a yükledik hocam.
